### ISSUE TITLE
s/accessor_facade/accessor-facade/ ?

### ISSUE THREAD

**Issue by lizmat** [jonathanstowe/AccessorFacade#1]
Why the use of underscore?   :-)

**Comment by jonathanstowe** [comment]
Because [Shift] + - is too hardwired in my fingers after years of doing languages that don't allow '-' in identifiers ;-)  I'll probably be making another release before I'm done with the reason I wrote it in the first place, plenty o' time for a deprecation cycle :-D

**Comment by jonathanstowe** [comment]
Actually, after almost a whole day of actually using it in something else I think that the interface isn't rich enough for what I need, so it may get changed sooner rather than later :)

**Comment by jonathanstowe** [comment]
There, the v0.0.2 deprecates the accessor_facade - it'll probably be closely followed up by a v0.0.3 as there are some hacky things in there ;-)
