### ISSUE TITLE
aAfter and before as named arguments

### ISSUE THREAD

**Issue by FCO** [jonathanstowe/AccessorFacade#2]
Just a idea: couldn't before and after be named arguments? I mean adverbs...
I think that is accessor-facade(&bla, &ble, :&after) or something like that would be great!

Great module, thanks!

**Comment by FCO** [comment]
Maybe even accessor-facade(:setter(&bla), :getter(&ble), :&after)

**Comment by jonathanstowe** [comment]
Hi,
yeah I actually decided that this would be a better interface some while ago as subsequently I found there are interfaces that require various permutaions of  the getter, setter, before and after that doesn't play nicely with positional arguments, I only didn't do it at the time as I didn't want to go back and change all the existing things that use it :)

So, yes, it's a good idea and I will do it at some point.

Thanks,

**Comment by jonathanstowe** [comment]
Hi,
I'm going to re-open this as I'll forget otherwise.

**Comment by jonathanstowe** [comment]
Hi,
v0.0.5 contains a named option, I have gone in the first place for all named parameters  or all positionals but I may add mixed later if this works out.

Thanks again for the suggestion.

**Comment by FCO** [comment]
😊
